version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: sh -c "gunicorn main.wsgi:application --bind 0.0.0.0:8031"
        restart: always
        volumes:
            - static_volume:/home/hplivestreaming/web/staticfiles/
            - media_volume:/home/hplivestreaming/web/media/
        expose:
            - 8031
        env_file:
            - ./.env.prod
        depends_on:
            - db
        networks:
            - hpd_alfa_be_backend-network
    db:
        image: postgres:15.4-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5452:5432
        env_file:
            - ./.env.db.prod
        restart: always
        networks:
            - hpd_alfa_be_backend-network
networks:
  hpd_alfa_be_backend-network:
   external: true
volumes:
    postgres_data:
    static_volume:
    media_volume:
    django_logs_volume:
