version: '3.8'

services:
    # web:
    #     build: .
    #     command: python manage.py runserver 0.0.0.0:8000
    #     volumes:
    #         - ./:/home/hplivestreaming/web
    #     ports:
    #         - 8000:8000
    #     env_file:
    #         - ./.env
    #     depends_on:
    #         - db
    db:
        image: postgres:15.4-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5452:5432
        env_file:
            - ./.env.db.dev
        restart: always
        networks:
            - backend
            - frontend
networks:
    backend:
        external: true
    frontend:
        external: true
volumes:
    postgres_data:
